### ISSUE TITLE
Critical error on all Cameras

### ISSUE THREAD

**Issue by DJFlaxi** [nibi79/synologysurveillancestation#53] opened 2022-06-29 08:58 UTC
2022-06-29 10:56:57.552 [ERROR] [tation.internal.thread.SynoApiThread] - DeviceId: 3; Thread: Snapshot; Critical error:

java.lang.NumberFormatException: For input string: "1.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThreadSnapshot.refresh(SynoApiThreadSnapshot.java:49) ~[bundleFile:?]
	at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread.runOnce(SynoApiThread.java:135) [bundleFile:?]
	at org.openhab.binding.synologysurveillancestation.internal.thread.SynoApiThread$1.run(SynoApiThread.java:67) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Pavion** [comment] 2022-06-29 15:55
This is a known issue with the latest OH 3.3.0-STABLE, please check this thread:
https://community.openhab.org/t/parsing-integer-config-entries-results-in-an-error-since-3-3-0-stable/136960
Workaround: change stream ID to 2 and then back to 1, it should work until restart.
I hope to get some additional information on this issue and will report back asap.

**Comment by Pavion** [comment] 2022-07-03 12:36
@DJFlaxi Please check the latest release (and its notes) here:
https://github.com/nibi79/synologysurveillancestation/releases/tag/3.3.0.202207031140
Feedback greatly appreciated!

**Comment by DJFlaxi** [comment] 2022-07-05 06:44
@Pavion Thx. But there is a new Error:
[ERROR] [nternal.thread.SynoApiThreadSnapshot] - Unexpected exception while obtaining snapshot, possibly network disconnected

**Comment by Pavion** [comment] 2022-07-05 15:26
Well it *is* a new message which shouldn't normally occur. 
It was intended as a fix for https://github.com/nibi79/synologysurveillancestation/issues/52 and occurs only if obtaining snapshot goes south for unexpected reason.
Is it a breaking issue for you?

**Comment by Pavion** [comment] 2022-07-10 10:19
Closing issue with the official Marketplace release. NPE or the mentioned error may occur once upon binding update or on configuration change, which issue might be addressed later.

**Closed as completed by Pavion** 2022-07-10 10:19 UTC
Labels: bug
