### ISSUE TITLE
Upgrade to openHAB 3.2.0 release

### ISSUE THREAD

**Issue by ahielg** [nibi79/synologysurveillancestation#50] opened 2021-12-20 15:32 UTC
Please upgrade the version to the latest openHAB release v 3.2.0

**Comment by Pavion** [comment] 2021-12-20 16:41
Are you using the latest release? 
I've just tested it on 3.2.0 without any issues:
https://github.com/nibi79/synologysurveillancestation/releases/tag/3.1.0.202101291345

**Comment by ahielg** [comment] 2021-12-20 16:51
Yes, and see instead of a camera image a broken image icon.

**Comment by Pavion** [comment] 2021-12-20 16:58
Please provide some more information and I'll look into it tomorrow
- was it working before and is not working after update? 
- have you tried to restart your openHAB?
- please check your credentials 
- bridge and thing status (ONLINE or any error)
- any related log entries in your openhab.log

**Comment by ahielg** [comment] 2021-12-20 17:48
Worked before upgrade, and not working after update.
I restarted openhab twice since the update
bridge is online and credentials are good.
Log error:2021-12-20 18:13:55.881 [ERROR] [ncestation.handler.SynoCameraHandler] - initialize camera: id 3 - Outdoor camera1::synologysurveillancestation:camera:XXXXXXXXXXXX:3

**Comment by Pavion** [comment] 2021-12-21 09:45
My setup still works as intended and I was unable to find any error out of the hand.  
It might be related to PTZ or patrol functions, which are not supported by my cam and can't be tested.
Anyway I've recompiled the binding against 3.2.0 and drafted a new release with an extended error output:
https://github.com/nibi79/synologysurveillancestation/releases/tag/3.2.0.202112210930
Could you please try this release and send me this exception text if/after it fails again?
Thanks in advance!

**Comment by ahielg** [comment] 2021-12-21 12:49
Now it is working! thanks!
BTW What is required in order for it to be an integral part of openHAB bindings?

**Comment by Pavion** [comment] 2021-12-21 13:19
Nice to hear! I still don't understand what was wrong but I'm glad it works now. 
Keep me posted if you encounter your issue again. 

As for being an integral part: this is a small scale project and I'm not able to provide any prolonged support. 
In other words, being standalone allows me to be lazy at will :)

**Comment by ahielg** [comment] 2021-12-27 15:54
If you put it there, wouldn’t the community maintain it along with you? That way you will not be alone....

**Comment by Pavion** [comment] 2021-12-28 09:04
I'm not even using this binding myself anymore as I've moved on to other devices but until now no one showed any interesse to participate. I admit I haven't tried it, but I'm not sure anyone would maintain it along if committed to backbone. On the other hand, moving there is a lot of work and rules to follow. 

I'm content to have a nice forum thread, so anyone searching for it will find it asap 
https://duckduckgo.com/?q=synology+binding+openhab&va=b&t=hc&ia=web
and anyone willing to participate is welcome in any case 🙂

**Comment by grouchal** [comment] 2021-12-28 10:23
@Pavion I think the best think would be to move it to the backbone so that it is visible and will automatically be recompiled for each update of openhab.

What are the problems in moving it there?

**Comment by Pavion** [comment] 2021-12-28 10:32
Hi @grouchal!
We do have to abandon this repo and move to openhab-addons, don't we? 
It's kind of easier and clearer to own a repo and not having to pull a large repository behind. 
Also I'm not quite happy with resigning everything with my real name and in any case have to ask my collaborator for consent.

**Comment by jlaur** [comment] 2021-12-29 23:39
> I'm not even using this binding myself anymore as I've moved on to other devices but until now no one showed any interesse to participate.

I'm using your binding - so thanks for publishing it! :) I think it might work the other way around. If you would contribute the binding to the [openhab-addons](https://github.com/openhab/openhab-addons) project, people might be willing to participate with PR's towards the official addons repo. At least I have recently grown a habit of trying to fix any problems I encounter in the bindings I'm using. I prefer contributions towards the official repo since it's community-driven and has a high chance of being maintained. Sometimes you even see scripts being run for all bindings (e.g. providing i18n texts) or developers searching the codebase for specific problems to be fixed in all bindings after being discovered in one binding.

If you are not even using your own binding anymore, we can probably assume that you lost some interest in developing it further? I think it would be even more beneficial for you **and** the community if it would become an official binding.

Of course providing a PR with a new binding towards openhab-addons requires some work to address review comments before approval. Let me know if I can help/assist you in any way. I can even start reviewing the code and provide PR's towards your repo to fix some issues that would otherwise come up in review. But in that case end goal should be PR towards openhab-addons. :)

Alternatively you can publish it for the Community Marketplace.

Again, thanks for the binding!

**Comment by Pavion** [comment] 2021-12-30 09:26
First of all: thank you all for your kind words! 

This binding is already on Community Marketplace and is very easy to find. 
https://community.openhab.org/t/synology-surveillance-station-binding/129293

I haven't lost my interest in developing either. I just moved on to another device. I still fix errors (as in this issue) and could implement new features... but no one have asked for any for a long time. 

Please don't understand me wrong: I love OH and I like to contribute. I just don't see any benefits and many downsides of an integration. I have some questions / issues to understand, perhaps you could point out some answers:

- Lifecycle of an integrated binding

It is a very small binding and I'm supporting it mostly alone. Some features of this binding (Pan/Zoom) I can't even test myself as I don't have this kind of equipment. Thus the binding is to be considered error prone. Being standalone allows me to react fast and to draft a new release. Being integrated I have to wait for a next rollout or - yet again - provide a jar myself. 

- Repository handling  

As asked above: I assume I have to abandon this repo, all commit history, issues and so on and have to move in a huge ever changing repo? From my point of view, it'd obfuscate the development and obstruct issue handling. 

- Real name 

Yeah, it might be just a quirk but I really don't like to include my real name. 
I assume it's quite easy for any qualified person to find it out somehow and mostly I don't care. But this alias is used in all my projects and forums and I'd like to keep it recognizable. My real name is known to GitHub and used for commit authentication anyway. 

- Different expectations 

I just want to make a small point here, open for discussion. 
Having to search for and to integrate a jar file from GitHub presents in my opinion a kind of "firewall". Anyone to have done this is more likely to overcome small issues and provide an useful feedback on larger issues. 
On the other hand an integrated binding might double the user count but quadruple the question flood instead. 
As the latest log4shell discussion showed, even open source software makes people expect wonders :) 

- Small conclusion

If you've read this far :), please don't understand it as a fending off. 
This binding is almost four years old and the question of integration was arisen several times already. 
Each time I've understood no benefits and gained no collaborators but I'm open and looking forward for suggestions and discussions.  

And in any case thanks again for your feedback!! 
BR Pav

**Comment by jlaur** [comment] 2022-01-16 22:07
Hi Pavion,

Sorry for the late reply. I've had a busy start of the year, and also became add-ons maintainer since last time. These are still my personal opinions, mostly unaffected by this new role. :-)

> This binding is already on Community Marketplace and is very easy to find. https://community.openhab.org/t/synology-surveillance-station-binding/129293

That's cool, didn't know that. Switched from JAR to the Marketplace version for easier tracking - thanks.

> I haven't lost my interest in developing either. I just moved on to another device. I still fix errors (as in this issue) and could implement new features... but no one have asked for any for a long time.

Good to hear, thanks.

> * Lifecycle of an integrated binding
> 
> It is a very small binding and I'm supporting it mostly alone. Some features of this binding (Pan/Zoom) I can't even test myself as I don't have this kind of equipment. Thus the binding is to be considered error prone. Being standalone allows me to react fast and to draft a new release. Being integrated I have to wait for a next rollout or - yet again - provide a jar myself.

Correct, for feedback during development/testing phase procedure is the same - provide jar's.

> * Repository handling
> 
> As asked above: I assume I have to abandon this repo, all commit history, issues and so on and have to move in a huge ever changing repo? From my point of view, it'd obfuscate the development and obstruct issue handling.

Yes, code would have a new home. So there would be an initial commit with current code and no history. Also new issues would have to be created for that repo. You could still keep your current repo though for the sake of keeping git history. Perhaps it could also be possible to redo all commits for new PR towards openhab-addons repo, but would have to ask maintainers since usual procedure is squash-merge for each PR.

> * Real name
> 
> Yeah, it might be just a quirk but I really don't like to include my real name. I assume it's quite easy for any qualified person to find it out somehow and mostly I don't care. But this alias is used in all my projects and forums and I'd like to keep it recognizable. My real name is known to GitHub and used for commit authentication anyway.

Can't argue with that, real name is required for sign-off, yes.

> * Different expectations
> 
> I just want to make a small point here, open for discussion. Having to search for and to integrate a jar file from GitHub presents in my opinion a kind of "firewall". Anyone to have done this is more likely to overcome small issues and provide an useful feedback on larger issues. On the other hand an integrated binding might double the user count but quadruple the question flood instead. As the latest log4shell discussion showed, even open source software makes people expect wonders :)

I understand, but actually you probably wouldn't have to deal with more user requests than now, since you would have the community behind you. And now it's not a jar anymore, since you uploaded to Marketplace, so question flood should already be a problem? :-) Usually new users tend to ask in community forum first before creating issues. And many other users will usually help. You would only have to deal with actual bugs/issues created, and you wouldn't even be alone. Others would help assessing whether it's actually a bug, etc.

> * Small conclusion
> 
> If you've read this far :), please don't understand it as a fending off. This binding is almost four years old and the question of integration was arisen several times already. Each time I've understood no benefits and gained no collaborators but I'm open and looking forward for suggestions and discussions.

You should do what ever you prefer and feel comfortable with. :-) Let me just highlight also a few advantages, since you pointed out some disadvantages:
- Some of the routine stuff can/will be handled by others or scripts written by others. For example upgrading libraries, fixing a bug which is the same within all bindings, migrating all bindings after breaking openhab-core API changes, etc.
- Translations will be provided by the community through Crowdin.
- Over time some other developers might pick up interest for your binding and will start to contribute with bugfixes or even new features. You will still be code owner and reviewer of pull requests. Others might even help adapting when Synology changes something that breaks the binding.
- Backup/trust: You could delete your GitHub account or repository today, and it would disappear. Probably you won't (hopefully), but this is more unlikely to occur with the openhab-addons repository, and also a lot of people have it, so it won't just disappear.
- I contribute to multiple bindings. Having a single repository makes it a lot easier for me to do this, than if I would have to clone multiple personal repositories with different distribution methods. So for me as a developer it's just easier, and I'm more likely to contribute.

> And in any case thanks again for your feedback!! BR Pav

You're welcome and thanks again for the binding. Here's one of my use-cases:
https://techblog.vindvejr.dk/?p=503

/Jacob

**Comment by Pavion** [comment] 2022-01-22 10:33
Hi Jacob and sorry too, I had my holidays at the start of the year but the last week just kicked in with all the old stuff again 😞 
Thank you for your extended reply! 

> That's cool, didn't know that. Switched from JAR to the Marketplace version for easier tracking - thanks.

I admit, until last week I wasn't even aware of the fact, that Marketplace bindings are searchable and downloadable from GUI. 
I'm upgrading my setup with each major release but seldom check the new features. But as it goes, I now find this Marketplace just cool, it's exactly what I've wanted.

> So there would be an initial commit with current code and no history. 

That's a pity. For me as a casual coder it's easier to keep track, avoid or amend errors by using a single repository. 

> * Some of the routine stuff can/will be handled by others or scripts written by others. For example upgrading libraries, fixing a bug which is the same within all bindings, migrating all bindings after breaking openhab-core API changes, etc.

Actually I do like major code breaks. It makes me revisit my code, rethink and rewrite some stuff 😈  

> * Translations will be provided by the community through Crowdin.

I've learned something new today ©️ 
Never heard of before but it's a cool thing! 

> * Backup/trust: You could delete your GitHub account or repository today, and it would disappear. Probably you won't (hopefully), but this is more unlikely to occur with the openhab-addons repository, and also a lot of people have it, so it won't just disappear.

That's right. I promise not to🙂 
As I've just found out deleting a repository makes one of its forks to a new parent. Nice!  

> * I contribute to multiple bindings. Having a single repository makes it a lot easier for me to do this, than if I would have to clone multiple personal repositories with different distribution methods. So for me as a developer it's just easier, and I'm more likely to contribute.

I think as long as I'm able to offer further support and no new contributors arrive I'll stay here. If my Synology NAS breaks, I'm not sure I'll replace it. In this case I'll sure consider the integration before abandoning it altogether.     

> You're welcome and thanks again for the binding. Here's one of my use-cases: https://techblog.vindvejr.dk/?p=503

Awesome solution! On my holidays I've upgraded my fish tank with a cam and a smart Z-Wave water temperature sensor, which controls the heating. Kind of basic, compared... 😄  

BR Pav

**Comment by Pavion** [comment] 2022-02-12 07:50
_Purging old issues_
Thank you all again for the contribution and feedback! 👍

**Closed as completed by Pavion** 2022-02-12 07:50 UTC
